### ISSUE TITLE
Guess repository name from git remote

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/sbt-github-release#2]
Set default `GithubRelease.repoName` from git config if possible, else org/name as now. One way to get the url:

```
git ls-remote --get-url origin
```

from [SO](http://stackoverflow.com/a/16880000/736957)

**Comment by vshalts** [comment]
Hi,
I think I have a fix for this. Please review - https://github.com/ohnosequences/sbt-github-release/pull/27
