### ISSUE TITLE
NoClassDefFoundError with Java 10

### ISSUE THREAD

**Issue by etorreborre** [ohnosequences/sbt-github-release#28]
I am using v0.5.0 with Java 10 and starting sbt I got
```scala
 java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
```

My work around is to add the following option to `.sbtopts`
```
-J--add-modules=java.activation
```

**Comment by hyst329** [comment]
However, it doesn't work with Java 11 anymore (since the `java.activation` module seems to be removed completely, rather than deprecated)

**Comment by SethTisue** [comment]
on JDK 11, add this to `projects/plugins.sbt` to make it work:

```scala
libraryDependencies += "com.sun.activation" % "javax.activation" % "1.2.0"
```

**Comment by hyst329** [comment]
@SethTisue It's done in #29 (since it must be a dependency of the _plugin_, not _project_)

**Comment by etorreborre** [comment]
Closing this old issue now.
