### ISSUE TITLE
More options for credentials

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/sbt-github-release#9]
- a setting [`=> Github`](http://github-api.kohsuke.org/apidocs/org/kohsuke/github/GitHub.html) instance so that user can set it with the java API directly using preffered credentials
- use default file/env chain otherwise, explain it in the readme

**Comment by EmilDafinov** [comment]
Would you really want it to be a setting of type `GitHub`? Given that you are looking to change the library (https://github.com/ohnosequences/sbt-github-release/issues/17), it seems a bit counterproductive to expose a class of that library to the user. Wouldn't it be better to define a case class for github credentials as the type of the setting? That way you won't break backwards compatibility when you change the underlying github library?

**Comment by EmilDafinov** [comment]
Also, a question regarding the location where the credentials are stored: currently it is in a file called `.github` in the user's home directory. Is this a standard place for storing github related configuration, or is it a specific requirement for this plugin?

**Comment by laughedelic** [comment]
> Would you really want it to be a setting of type GitHub? Given that you are looking to change the library (#17), it seems a bit counterproductive to expose a class of that library to the user.

You are right 👍  This is an old issue and I forgot to update it after deciding on #17. The title though stays correct: regardless of the underlying library, it should be possible to set credentials in different ways. 

> Wouldn't it be better to define a case class for github credentials as the type of the setting? That way you won't break backwards compatibility when you change the underlying github library?

This makes sense, but I'd like to keep things simple. I will take a look at #20 tonight and tell you want I think. I'd like to discuss it first before digging too much into a particular implementation.

**Comment by laughedelic** [comment]
This got covered by #20.
